backend:
  name: github
  branch: main
  repo: "bennihtm/blog"           # <-- This should identify the repo for your website
  base_url: https://decap.bennihtm.xyz    # <-- This should contain your PROXY URL
  auth_endpoint: /auth

media_folder: src/assets
public_folder: /assets

collections:
  - name: post
    label: Posts
    label_singular: Post
    folder: src/content/post
    create: true
    path: "{{slug}}/index"
    extension: mdx
    format: frontmatter
    slug: "{{slug}}"
    identifier_field: title

    # Store media relative to each post's directory.
    media_folder: ""
    public_folder: ""

    fields:
      - name: title
        label: Title
        widget: string
        required: true
        pattern:
          - ".{1,120}"
          - "Maximum 120 characters."

      - name: description
        label: Description
        widget: text
        required: true
        pattern:
          - ".{1,160}"
          - "Maximum 160 characters."

      - name: coverImage
        label: Cover Image
        widget: object
        required: false
        collapsed: true
        fields:
          - name: src
            label: Image
            widget: image
            required: true
            media_folder: images
            public_folder: ""
            choose_url: false

          - name: alt
            label: Alt Text
            widget: string
            required: true

      - name: draft
        label: Draft
        widget: boolean
        required: false
        default: false

      - name: ogImage
        label: Open Graph Image
        widget: image
        required: false
        media_folder: images
        public_folder: ""
        choose_url: false

      - name: publishDate
        label: Publish Date
        widget: datetime
        required: true
        date_format: "YYYY-MM-DD"
        time_format: "HH:mm"
        picker_utc: false

      - name: tags
        label: Tags
        widget: list
        required: false
        default: []
        field:
          label: Tag
          name: tag
          widget: string

      - name: updatedDate
        label: Updated Date
        widget: datetime
        required: false
        date_format: "YYYY-MM-DD"
        time_format: "HH:mm"
        picker_utc: false

      - name: body
        label: Body
        widget: markdown
        required: true